name = "sky-dump-webhook"
main = "webhook.ts"
compatibility_date = "2023-12-01"

[[kv_namespaces]]
binding = "UPLOAD_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[env.preview.vars]
JWT_SECRET = ""
EMAIL_WORKER_URL = "https://sky-dump-email.your-subdomain.workers.dev"
WEBHOOK_SECRET = ""

[env.development.vars]
JWT_SECRET = "dev-secret-key-change-in-production"
EMAIL_WORKER_URL = "http://localhost:8789"
WEBHOOK_SECRET = "dev-webhook-secret"

# Routes for the webhook worker
[[routes]]
pattern = "*/webhook/*"
zone_name = "your-domain.com"
