name = "sky-dump-upload"
main = "upload.ts"
compatibility_date = "2023-12-01"

[[kv_namespaces]]
binding = "UPLOAD_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[env.production.vars]
CLOUDFLARE_ACCOUNT_ID = ""
R2_ACCESS_KEY_ID = ""
R2_SECRET_ACCESS_KEY = ""
R2_BUCKET_NAME = ""
JWT_SECRET = ""

[env.preview.vars]
CLOUDFLARE_ACCOUNT_ID = ""
R2_ACCESS_KEY_ID = ""
R2_SECRET_ACCESS_KEY = ""
R2_BUCKET_NAME = ""
JWT_SECRET = "dev-secret-key-change-in-production"

# Routes for the upload worker
[[routes]]
pattern = "*/upload/*"
zone_name = "your-domain.com"
