name = "sky-dump-auth"
main = "auth.ts"
compatibility_date = "2023-12-01"

[env.production.vars]
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_REDIRECT_URI = "https://sky-dump.pages.dev/auth/callback"
JWT_SECRET = ""

[env.preview.vars]
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_REDIRECT_URI = "http://localhost:4321/auth/callback"
JWT_SECRET = "dev-secret-key-change-in-production"

# Routes for the auth worker
[[routes]]
pattern = "*/auth/*"
zone_name = "your-domain.com"
